spring:
  application:
    name: projetoaula

  datasource:
    url: jdbc:postgresql://localhost:5432/registro_usuarios
    username: murilo
    password: 123
    driver-class-name: org.postgresql.Driver
    initialize: true

  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgres

server:
  port: 8080
